name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup nuget
      uses: nuget/setup-nuget@v1
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore src/Elmah.Io.Uno/Elmah.Io.Uno.csproj
    - name: Build
      run: msbuild src/Elmah.Io.Uno/Elmah.Io.Uno.csproj -p:Configuration=Release
    - name: Pack
      run: nuget pack Elmah.Io.Uno.nuspec -Version 4.0.${{ github.run_number }}-pre -Properties Configuration=Release -Properties Commit=${{ github.sha }}
    - name: Push
      run: dotnet nuget push Elmah.Io.Uno.4.0.${{ github.run_number }}-pre.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}
