name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Setup nuget
      uses: nuget/setup-nuget@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          5.0.x
          8.0.x
    - name: Uninstall .NET workload
      run: dotnet workload clean --all
    - name: Run uno-check
      shell: bash
      run: |
        dotnet tool install --global Uno.Check --version 1.20.0
        uno-check -v --ci --non-interactive --fix --skip vswin --skip androidemulator --skip androidsdk
    - name: Install dependencies
      run: dotnet restore src/Elmah.Io.Uno/Elmah.Io.Uno.csproj
    - name: Build
      run: msbuild src/Elmah.Io.Uno/Elmah.Io.Uno.csproj -p:Configuration=Release
    - name: Pack
      run: nuget pack Elmah.Io.Uno.nuspec -Version 5.0.${{ github.run_number }}-pre -Properties Configuration=Release -Properties Commit=${{ github.sha }}
    - name: Push
      run: dotnet nuget push Elmah.Io.Uno.5.0.${{ github.run_number }}-pre.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
      if: ${{ github.event_name == 'push' }}
